### ISSUE TITLE
Unable to resize Task Manager

### ISSUE THREAD

**Issue by aj752** [aasmal97/Window-Actions#10]
First of all, thank you for making this plugin. I just found it and it has been a lifesaver for a workflow I'm working on. 

I'm unable to resize Task Manager, is this due to privilege limits? Everything is working perfectly.

Thanks!

**Comment by aasmal97** [comment]
Hey @aj752 !

So I can help identify the issue

- When you are resizing, are you trying to make Task Manager smaller, or larger, or both ? 
- What identifier (title, partial title, process name (.exe file)) are you using to resize

**Comment by aj752** [comment]
Thank you for the quick reply. I tried all different combinations, Task Manager just doesn't respond to it. Other applications work as intended. I tried partial title, process name dropdown, exact name.

**Comment by aasmal97** [comment]
@aj752 Gotcha!

It may be related to a bug that arises when we identify ids for active windows, but I'll have to test to be sure. I'll take a look into it, and get back to you. 

For now, I'll open up an issue and mark this as a potential bug.

You can track the issue to get notified when it resolves.

**Comment by aj752** [comment]
Sounds awesome, appreciate it! 

If you don't mind me sharing an idea, it would be cool to have a checkbox that when checked brings the resized window to the front. If you are like me and have lots of windows open all the time it is very useful. Not sure if it is even possible, just a suggestion. Take care!

**Comment by aasmal97** [comment]
> First of all, thank you for making this plugin. I just found it and it has been a lifesaver for a workflow I'm working on.
> 
> I'm unable to resize Task Manager, is this due to privilege limits? Everything is working perfectly.
> 
> Thanks!

![image_2023-11-24_164959632](https://github.com/aasmal97/Window-Actions/assets/74555081/7ba6051b-d001-4a8a-8c91-1ea5e2241379)

Looks like your initial assumption @aj752 was right :) ! It looks like a privilege issue, and after further research, I found that Task Manager does run with elevated permissions. This is usually a good thing since it prevent malware from manipulating, and reading it contents :) 

I'm unsure if this will work, since I don't have my StreamDeck on me, but you could run force the Elgato Stream Deck app to run as an administrator and see if that resolves this issue. Unfortunately, there not much a plugin can do to elevate it's own permissions, since we run inside the container of the stream deck app. 

If I try to programmatically circumvent this, I run the risk of the plugin becoming seen as malware, and a security vulnerability/opening in an otherwise secure system. 

I will look into your suggestion of adding a focusing checkbox, but perhaps I may introduce an independent focus window action, which you can group together in a multi-action to achieve the same functionality.

**Comment by aj752** [comment]
I feel a bit stupid but will share anyway = I did try to run as administrator, right-click from my task bar, choose run as administrator. This did not work, after that I reported here. Now I went back to the actual .exe and change the property on the file. Now when I launch Stream Deck i get UAC, click yes to continue and it is working. 

Looking forward to see future updates, I need lots of automation for screen recordings and this one has saved me a huge pain to go through every single time. Thanks again!
