### ISSUE TITLE
"select identifier" not working

### ISSUE THREAD

**Issue by kangsehun123** [aasmal97/Window-Actions#13]
![not working](https://github.com/aasmal97/Window-Actions/assets/132452939/3ac245e8-6802-466c-ac73-3f30b73204b8)

Even when I click “select identifier”, there is no response as shown in the picture.

**Comment by aasmal97** [comment]
Hi @kangsehun123 !

So I can debug this, please give me you Windows version (i.e build number and version)

If you pull up your computer's "About" page, it should be listed.

**Comment by kangsehun123** [comment]
I formatted my computer a week or two ago and reinstalled StreamDeck, but it cannot be set up. The OS build and version are 19045.4123 /22H2. Thank you and respect you for your service.

**Comment by kangsehun123** [comment]
문제는 이 해결 되지 않았다 .종결 버튼을 잘못 눌렀다

**Comment by aasmal97** [comment]
Ah okay. You're running Windows 10 then. Unfortunately I no longer have a Windows 10 system to test this issue on, but I assume the latest Windows 10 update has caused this issue. (I.e update on Feb 29th, 2024).

It is probably related to a crash when our virtual desktop actions initiate, and error is unhandled, since without it, no virtual desktop action can work (i.e creating new virtual desktop, moving windows to a virtual desktop, and navigating through virtual desktops). This error causes the entire server to crash (i.e no actions to work)

However, not having this feature set would severely impact this app, so to fix, I need to test the binaries, and see which one will work. This may take some time, since I'll need to test this on a Windows 10 computer.

**Comment by aasmal97** [comment]
Hey @kangsehun123 just created a new release, which I believe restores functionality on Windows 10. If you are still using this plugin, feel free to download the new [release](https://github.com/aasmal97/Window-Actions/releases/tag/v4.2.0) or wait for the Elgato Marketplace to publish it :) !
