### ISSUE TITLE
This product causes major problems on WIN10 (As you already know) .  

### ISSUE THREAD

**Issue by wwsoapbox** [aasmal97/Window-Actions#15]
Does not work on WIN aand can not be uninstalled.  It should never have been released .  Shame on you.  These is no warning on the Elgato web download site.

**Comment by aasmal97** [comment]
Hey @wwsoapbox I apologize for your experience, and for this late response. 

I released this app because I wanted to share a tool that I created, that has helped me become more productive, with everyone. That said, I completely understand that when software breaks it is incredibly frustrating and I've been on the other end of that countless times. 

However, I maintain this app during my spare time, and unfortunately I've been busy the past couple of months and have not had time to resolve the issue that this plugin ran into, upon a Windows 10 update in February, when the problems began on Windows 10.

Luckily I found some spare time now, but unfortunately I no longer have a Windows 10 machine so it is tricky for me to test and resolve this. However, I released version 4.2.0 and it should, at the minimum, patch any crashing issues that the plugin was encountering. 

That said, due to my inability to test on a Windows 10 machine for the time being, virtual desktop actions may not work yet, but all other action functionality has been restored. 

If despite this, you wish to uninstall the plugin, you are more than welcome to. You can simply open up your file explorer, and go to 

`%APPDATA%/Elgato/StreamDeck/Plugins/com.arkyasmal.windowactions.sdPlugin` and delete the folder. This will remove all traces of the plugin for you.

Since Windows 10 deprecates today, and Windows 10 compatibility has been sufficiently mitigated with this new release, I will closing this issue
