### ISSUE TITLE
Focus Window action does not function while ApplicationFrameHost.exe is focused

### ISSUE THREAD

**Issue by StardustD2** [aasmal97/Window-Actions#16]
Just as the title says, while `ApplicationFrameHost.exe` is focused, I am unable to use the `Focus Window` action to bring any other window into focus. I'm on Win11 Pro 23H2 build 22631.4037 if that's relevant.

Some examples of programs running as `ApplicationFrameHost.exe`: `Microsoft To Do` and the native `Settings` app

**Comment by aasmal97** [comment]
This is an interesting issue. 

However, this may be a permissions issue.

By default the StreamDeck app runs without admin permissions. If the Stream Deck doesn't run with admin permission then the plugin also doesn't have admin permission. This makes sense since the plugin runs in a container environment, that the StreamDeck app provides, and therefore we cannot have higher permissions than what the StreamDeck app has.

To fix this, you may have to elevate the StreamDeck app's permission to always run as administrator if you are targeting windows or applications that have `ApplicationFrameHost.exe`, since these are usually CORE system applications, that only admins/current users have access to. Note, you would actually have the same issue trying to target the Task Manager because of this, as referenced here: #10 

To elevate your permissions refer to this.
This is [guide](https://www.xda-developers.com/how-tun-run-apps-administrator-windows-11/) that I found on how to do this

Let me know if this fixes your issue :)

**Comment by aasmal97** [comment]
This is fixed in new release ver 4.2.0 :) ! Thanks for the report. 

I was able to potentially circumvent the permissions issue, by not failing the script  when `AttachThreadInput`  returned a permission denied error, and allowing this step to pass through.

**Comment by StardustD2** [comment]
Glad to hear it! Will test it myself hopefully tomorrow without elevated privileges and I'll update this comment with the results if the fix solved my problem. Otherwise I'll send a new reply/open a new issue.
