### ISSUE TITLE
All functions KO with 3.0 ?

### ISSUE THREAD

**Issue by Toon49** [aasmal97/Window-Actions#9]
Hi, can't get anything to work with plugin 3.0, Win10 & SD 6.4.0.19687, did I missed something ?
All is ok with 2.2

**Comment by aasmal97** [comment]
Hey @Toon49

For initial troubleshooting:
- [ ] Have you tried uninstalling the plugin, and setting up your actions again, completely anew
- [ ] What actions are trying to use?
- [ ] What actions have given you failure feedback?
- [ ] What specific version of Windows 10 do you have (i.e the build number). This can be found by typing "about" in the windows search bar and clicking "about this PC"


Though incredibly rare, sometimes antivirus monitoring software can block executables, since our actions allow users to automate certain tasks that usually requires user input, (like moving virtual desktop windows). This causes causes false flags to be raised. 

Therefore: 
- [ ] Has your anti-monitoring software blocked any files? If so which ones ?

**Comment by Toon49** [comment]
Hi @aasmal97 
Yes I tried to uninstall/reinstal with no effects.
For exemple, close window action : I set up the .exe name but when I press the SD button it show the "error triangle" with no action ont the set window. It's the same result with all functions (minimize, maximize, Creat Virtuel desktop ...)
I haven't any specific antivirus, only integrated windows defender, using Win 10 Pro v10.0.19045 up to date.
All functions ok with plugin 2.2 witch I downgraded to

**Comment by aasmal97** [comment]
> Hi @aasmal97 Yes I tried to uninstall/reinstal with no effects. For exemple, close window action : I set up the .exe name but when I press the SD button it show the "error triangle" with no action ont the set window. It's the same result with all functions (minimize, maximize, Creat Virtuel desktop ...) I haven't any specific antivirus, only integrated windows defender, using Win 10 Pro v10.0.19045 up to date. All functions ok with plugin 2.2 witch I downgraded to

Unfortunately, I don't own a Windows 10 machine anymore, so this is difficult for me to test right now. However, I have some potential ideas about why this occurred, and in future versions, this may be resolved.

I'll be updating the ```pywin32``` library that exposes this API directly in a reliable way, to it's latest version. I'll also be updating any old code that may be using an outdated interface, to `pywin32` to ensure consistent dependencies. Finally I'll re-check my versioning logic, to see if I'm detecting the correct windows version properly as this could lead to improper code running on the wrong version. 

Until I can assure this problem won't arise on Windows 10 anymore, downgrading to 2.2.0, is the solution for now. 

Sincerely,
Arky Asmal
